# Generated by Django 4.2.17 on 2025-01-09 19:55

import os
from django.db import migrations


def create_superuser(apps, schema_editor):
    User = apps.get_model("users", "CustomUser")

    DJ_SU_EMAIL = os.environ.get("DJ_SU_EMAIL")
    DJ_SU_PASSWORD = os.environ.get("DJ_SU_PASSWORD")

    if not DJ_SU_EMAIL or not DJ_SU_PASSWORD:
        raise ValueError("Environment variables DJ_SU_EMAIL and DJ_SU_PASSWORD must be set.")

    User.objects.create_superuser(email=DJ_SU_EMAIL, password=DJ_SU_PASSWORD)


def delete_superuser(apps, schema_editor):
    User = apps.get_model("users", "CustomUser")
    DJ_SU_EMAIL = os.environ.get("DJ_SU_EMAIL")

    if not DJ_SU_EMAIL:
        raise ValueError("Environment variable DJ_SU_EMAIL must be set.")

    try:
        user = User.objects.get(email=DJ_SU_EMAIL)
        if user.is_superuser:
            user.delete()
        else:
            raise IndexError("The specified user is not a superuser.")
    except User.DoesNotExist:
        raise IndexError("The specified user does not exist.")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser),
    ]
